name: dependency ignore test
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # - uses: oluatosn-test-org/private-dependabot@v1
      - uses: oluatosn-test-org/private-checkout@v4
